name = "scc-food"
main = "src/index.ts"
compatibility_date = "2024-09-01"

[assets]
directory = "../frontend/public"

[[d1_databases]]
binding = "DB"
database_name = "scc-food"
database_id = "39d05335-244e-41b8-9082-4d98f5cd1db5"
